### ISSUE TITLE
No option for axes (Invert control)

### ISSUE THREAD

**Issue by Paderman** [jneilliii/OctoPrint-JogWheelControl#1]
Hello,
it's a nice alternative for the other control 😇 but I can't use "Invert control" for an axis like "Y". In the printer settings for the selected printer the checkbox for "Y" is set for "Invert control" but no changes. The direction for the bed must be have "Invert control", can you please add a function to read the settings from the current printer?

Thank you 🙂

**Comment by jneilliii** [comment]
I'll look into using the built in options from printer profile to do that.

**Comment by jneilliii** [comment]
added with the above commit and released as version 0.0.2.

**Comment by Paderman** [comment]
> added with the above commit and released as version 0.0.2.

Thank you very much for fixing this small problem fast 😇
