### ISSUE TITLE
"incompatible Plugin" 

### ISSUE THREAD

**Issue by Herbert-Testmann** [jneilliii/OctoPrint-JogWheelControl#2]
the plug in manager list JogWheelControl as a incompatible plugin on my OctoPrint Installation.
what can I do to find the reason?

**Comment by jneilliii** [comment]
The only limitation of the plugin is you must be running OctoPrint in Python 3.

**Comment by Herbert-Testmann** [comment]
OctoPrint runs on a RasPi. Is there a command line command to see the version?

**Comment by jneilliii** [comment]
At the bottom of the page under the file list you should see OctoPrint's and python versions listed.

**Comment by Herbert-Testmann** [comment]
Phyton 3.9.2
any Ideas ??

**Comment by jneilliii** [comment]
Strange, I can't think of any reason. The compatibility is set proper on the plugin repo.

![Screenshot_20240401-161235](https://github.com/jneilliii/OctoPrint-JogWheelControl/assets/5249455/5b1c201c-badc-4983-baae-22b37a1e1a41)

**Comment by jneilliii** [comment]
Are you able to hover over the incompatible indicator to see why, I think it gives description.

**Comment by Paderman** [comment]
I use _OctoPrint_ with _Docker_ and it works fine 🤷 😇
(_Docker_ and _Portainer_ under _Orange Pi Zero2_ with _Debian "Bookworm"_ 🫣)

**Comment by Herbert-Testmann** [comment]
There isn't any mouseover on Webinterface.
Is there another way to see the reason?
![image](https://github.com/jneilliii/OctoPrint-JogWheelControl/assets/20645041/a12bf880-3237-482e-ad50-3ce07b583950)

**Comment by Herbert-Testmann** [comment]
`pi@octopi:/ $ pip install "https://github.com/jneilliii/OctoPrint-JogWheelControl/archive/master.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/jneilliii/OctoPrint-JogWheelControl/archive/master.zip
  Downloading https://github.com/jneilliii/OctoPrint-JogWheelControl/archive/master.zip
     | 612 kB 1.2 MB/s
    ERROR: Command errored out with exit status 255:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-68apghbs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-68apghbs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-86lzp57z
         cwd: /tmp/pip-req-build-68apghbs/
    Complete output (1 lines):
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    ----------------------------------------
WARNING: Discarding https://github.com/jneilliii/OctoPrint-JogWheelControl/archive/master.zip. Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.`

**Comment by Herbert-Testmann** [comment]
pi@octopi:/ $ python3 -V
Python 3.9.2

**Comment by jneilliii** [comment]
Instead of trying to install into your system python, try going into plugin manager, get more, and copy/paste the URL into the ...from URL field and click install.

**Comment by Herbert-Testmann** [comment]
If I "and copy/paste the URL into the ...from URL field and click install."
nothing happens. No error, no plugin.

**Comment by jneilliii** [comment]
The version of python you mentioned earlier having may not be the one that OctoPrint is running under. Can you please share a screenshot of what you have underneath your file list, like this?

![image](https://github.com/jneilliii/OctoPrint-JogWheelControl/assets/5249455/bd2e53bc-908d-441b-a544-00fb3ab76a54)

**Comment by Herbert-Testmann** [comment]
<img width="450" alt="Bildschirmfoto 2024-04-04 um 13 03 42" src="https://github.com/jneilliii/OctoPrint-JogWheelControl/assets/20645041/8c914271-6d66-43e7-8e5c-3b3f8a79c32f">

**Comment by jneilliii** [comment]
Maybe because of your dirty OctoPrint version it's getting flagged as incompatible. At this stage I can only say it's something to do with your instance and not reproducible as an issue and others are using it fine so not sure how I'll be able to help. The only thing I can suggest at this point is creating a backup, download backup, reflash OctoPi on the SD card, restore backup and then try installing.
