### ISSUE TITLE
needs a home all button as well

### ISSUE THREAD

**Issue by Heathn66** [jneilliii/OctoPrint-JogWheelControl#3]
not really an issue but inconvenience need to have an auto home all button

**Comment by jneilliii** [comment]
As mentioned in #4 maybe making the home button command just be home all might be a better option. Do you ever use just home X/Y without homing Z? That could always be done manually if the need arises from the terminal tab. I was thinking for a future update though, that I might try to implement the esp3d version of jog control, which is much more robust. 

![image](https://github.com/jneilliii/OctoPrint-JogWheelControl/assets/5249455/8775de64-e957-4d47-a0c9-ca7afbe7e635)

**Comment by jneilliii** [comment]
Finally got around to switching over to the smoothieware webui imiplementation of the jog wheel control in the latest version 1.0.0 which includes a home all button.
