### ISSUE TITLE
Allow to move Z axis for more than 10mm

### ISSUE THREAD

**Issue by jbazant** [jneilliii/OctoPrint-JogWheelControl#4]
### Feature request
Allow to move Z axis for 0.1, 10, 100 mm instead of 0.1, 1, 10 mm.
**OR**
Allow to configure steps.

Thank you for your great UI plugin!

**Comment by jneilliii** [comment]
Maybe making the home button a "home all" button (#3) and making the z 0.1,1,10,100 might be a better option.

**Comment by jneilliii** [comment]
Added 100 z step with the latest version 1.0.2.
