### ISSUE TITLE
z-axis controls do not work anymore

### ISSUE THREAD

**Issue by Rednax74** [jneilliii/OctoPrint-JogWheelControl#5]
After the last update the z-Axis buttons do not work anymore. x- and y-axis controls work as well as the home buttons.
Jog Wheel Control (1.0.0)

**Comment by jneilliii** [comment]
please check the terminal tab after pressing the button, it's sending the command for me to move z.

![image](https://github.com/user-attachments/assets/bc4c9e16-1d6d-4684-b27f-b0874479d79e)

**Comment by Rednax74** [comment]
I checked it already, for x/y the commands are visible, for the z axis not. And if I disable your plugin, the standard z-axis controls work. 
But I'll double check.

**Comment by jneilliii** [comment]
Might have to get you to open your browser's developer tools and look for errors on page load or on z button clicks since this plugin is mostly javascript programming.

**Comment by Rednax74** [comment]
I am using Opera by the way, if I press the z-axis buttons this error message is shown in the concole:
![Screenshot 2024-08-26 084732](https://github.com/user-attachments/assets/094385ff-d9e4-4e97-98f9-d069e91f5b25)

**Comment by BeriBGood** [comment]
For me it is working for Z, but not for Y
Console shows this:
![image](https://github.com/user-attachments/assets/f2a64ea4-cfe6-4436-b7a4-cd3a4c582f18)

(Firefox)

**Comment by jneilliii** [comment]
Ok, so in both cases it's related to distance variable in the code, and that is being used to figure out if the axes is inverted or not I think. In all my testing I didn't ever have this issue, so it could be a timing problem, or a missing dependency to the printer profile information. 

~~@BeriBGood what browser are you using?~~ never mind, I see you added it to your post, sorry for missing that.

**Comment by BeriBGood** [comment]
Firefox 129.0.2 (64-bit)
Edge Version 128.0.2739.42 (Official build) (64-bit) also has the error for Y (X, Z and Homing work fine)

![image](https://github.com/user-attachments/assets/f988f098-bc1a-4e78-af59-886b769a681b)

The previous version of the plugin worked fine for me.
Something in the new version broke, if that helps you restrict the scope of the debugging.

**Comment by Rednax74** [comment]
Since my z-axis is inverted, maybe it is related to this setting. I'll test it without setting the z Axis to inverted maybe this works (If I can find the settings for that again :-) )

**Comment by Rednax74** [comment]
ok, I removed in the printer profile the invertion flag and without this being set it works again. 
In the previous version I am relatively sure that it worked also for the inverted z-axis.
Maybe it is a spelling error of the parameter?

**Comment by jneilliii** [comment]
Thanks, it does look like in the previous version I was defaulting those values in the function to null, and that may actually get past this random issue. I'll see about making that change tonight and release a new version and get you guys to test for me.

**Comment by jneilliii** [comment]
I've made some tweaks to the javascript side related to axes inversion. Could you guys please test for me prior to release? You can go into plugin manager > get more, copy/paste the URL below in ...from URL and click install.

```
https://github.com/jneilliii/OctoPrint-JogWheelControl/archive/refs/heads/master.zip
```

**Comment by BeriBGood** [comment]
Thank you, it works for me in all directions now.

**Comment by Rednax74** [comment]
Thanks a lot, it works also for me!

**Comment by jneilliii** [comment]
Thanks for the confirmation, new release has been published and is now live. There's nothing you guys will need to do because you'll already have the newer version installed.
