### ISSUE TITLE
Missing: settings page to change bed direction

### ISSUE THREAD

**Issue by Paderman** [jneilliii/OctoPrint-JogWheelControl#6]
Hello Jneilliii,
I re-installed OctoPrint and I can't find the settings page for this plugin... I must set reverse the bed if I want use the bed control, but when I press _+Y_, the bed is moving to _-Y_ and otherwise. I installed _UI Customizer_ or can I set manually the directions?
A settings page would be nice 🙂

Installed version: 1.0.2

**Comment by jneilliii** [comment]
That's done inside OctoPrint's printer profile settings on the axes tab.

![image](https://github.com/user-attachments/assets/ab0eee11-8828-46ba-bac5-1ef115ec8d21)

**Comment by Paderman** [comment]
I'm sorry, I'd forgotten after long time 🙈
I had to inverted the Y axes, now it works 🙂

I wish you a happy new year 🥳🙂😇
